### ISSUE TITLE
Enhancement: PVC template support of CollaSet

### ISSUE THREAD

**Issue by wu8685** [KusionStack/operating#104]
### What would you like to be added?

CollaSet supports stable storage like [StatefulSet](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#writing-to-stable-storage) in the way like `Spec.VolumeClaimTemplates`.

### Why is this needed?

Stable storage support is a standard capability of CollaSet.

**Comment by ColdsteelRail** [comment]
assign request
