### ISSUE TITLE
Enhancement: `PodUpdater` need refactoring to provide more general interface

### ISSUE THREAD

**Issue by wu8685** [KusionStack/operating#182]
### What would you like to be added?

A new [PodUpdater](https://github.com/KusionStack/operating/blob/v0.3.0/pkg/controllers/collaset/synccontrol/update.go#L257)  interface to cover Pod update lifecycle, so that users can easily extend a new Pod upgrade type.

### Why is this needed?

[PodUpdater](https://github.com/KusionStack/operating/blob/v0.3.0/pkg/controllers/collaset/synccontrol/update.go#L257) currently is not adaptable since Replace upgrade type includes. We need to refactor it to represent the Pod update behavior better.

**Comment by ColdsteelRail** [comment]
assign request
