### ISSUE TITLE
FeatureRequest: CollaSet supports operationDelaySeconds

### ISSUE THREAD

**Issue by wu8685** [KusionStack/operating#183]
### Is your feature request related to a problem? Please describe:

After preparing finished in PodOpsLifecycle, we still want to hold CollaSet process for a while before it delete or update Pods, in order to provide a grace period.

### Describe the feature you'd like:

When preparing finished in PodOpsLifecycle, it is supposed to hold for a while before CollaSet does operation on Pods. Take traffic for example, after traffic turned off, CollaSet need to wait for seconds before delete Pods to allow the traffic on the fly to be processed.

### Describe alternatives you've considered

Option 1 is to use Pod terminationGracePeriod, but it ask for users to handle TERM signal in application codes.
Option 2 is to ask users to consider the graceful process in preparing phase. For example, remove the PodOpsLifecycle protection finalizer only if all the traffic is processed completely.

All of above options ask users for extra effort. We still need to provide a way to make it easier.

**Comment by ColdsteelRail** [comment]
lifecycle.allowOps already support operationDelaySeconds

**Comment by ColdsteelRail** [comment]
lifecycle.allowOps already support operationDelaySeconds
