### ISSUE TITLE
Bug: controllerrevision of PodDecorations may need weight info

### ISSUE THREAD

**Issue by shaofan-hs** [KusionStack/operating#187]
### Minimal reproduce step

update pod which has a poddecoration with multi versions.

### What did you expect to see?

No panic, and controller works well.

### What did you see instead
paniced in
operating/pkg/controllers/utils/poddecoration.PodDecorations.Less(...)

### What is your KusionStack components and its version?

v0.3.0

**Comment by Eikykun** [comment]
already fixed in #168
